# Generated by Django 4.0.6 on 2022-10-13 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanagement', '0009_strategy_buy_nifty_strategy_nifty_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='user1',
            name='angel_token',
            field=models.CharField(default='SZB2BGTSNPPYOS52TFYQFP6M6E', max_length=100),
        ),
        migrations.AlterField(
            model_name='user1',
            name='angel_api_keys',
            field=models.CharField(default='NuTmF22y', max_length=100),
        ),
        migrations.AlterField(
            model_name='user1',
            name='angel_client_id',
            field=models.CharField(default='Y99521', max_length=10),
        ),
        migrations.AlterField(
            model_name='user1',
            name='angel_password',
            field=models.CharField(default='abcd@1234', max_length=100),
        ),
    ]
