# Generated by Django 4.0.6 on 2022-10-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanagement', '0010_user1_angel_token_alter_user1_angel_api_keys_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user1',
            name='expiry_3',
            field=models.CharField(default='NA', max_length=12),
        ),
        migrations.AddField(
            model_name='user1',
            name='working_days_3',
            field=models.IntegerField(default=0),
        ),
    ]
