# Generated by Django 4.0.6 on 2022-11-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanagement', '0013_user1_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='paper',
            field=models.CharField(default='on', max_length=10),
        ),
        migrations.AddField(
            model_name='user1',
            name='app_session_id_url',
            field=models.CharField(default='NA', max_length=1000),
        ),
    ]
